# Generated by Django 4.1.7 on 2023-03-29 11:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agency", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="area",
            constraint=models.UniqueConstraint(
                fields=("name",), name="unique_name_of_area"
            ),
        ),
    ]
