# Generated by Django 4.1.7 on 2023-03-29 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("agency", "0002_area_unique_name_of_area"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="search_area",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="clients",
                to="agency.area",
            ),
        ),
    ]
