# Generated by Django 4.1.7 on 2023-03-30 06:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agency", "0005_alter_property_agent"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="Additional_info",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="client",
            name="budget",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
