# Generated by Django 4.1.7 on 2023-03-30 06:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("agency", "0006_client_additional_info_client_budget"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="budget",
        ),
    ]
