# Generated by Django 4.1.7 on 2023-04-01 05:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agency", "0008_rename_additional_info_client_additional_info"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="deal",
            field=models.IntegerField(null=True),
        ),
    ]
