# Generated by Django 4.1.7 on 2023-04-01 06:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agency", "0010_remove_agent_deal_deal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deal",
            name="created_at",
            field=models.DateField(auto_now_add=True),
        ),
    ]
