# Generated by Django 4.1.7 on 2023-04-02 05:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agency", "0014_alter_deal_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="created_at",
            field=models.DateTimeField(),
        ),
    ]
