# Generated by Django 4.1.7 on 2023-04-05 04:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agency", "0016_alter_deal_date_alter_property_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="additional_info",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddConstraint(
            model_name="client",
            constraint=models.UniqueConstraint(fields=("email",), name="unique_email"),
        ),
    ]
