# Generated by Django 4.1.7 on 2023-04-05 19:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("agency", "0017_alter_client_additional_info_client_unique_email"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="client",
            name="unique_email",
        ),
        migrations.RemoveField(
            model_name="property",
            name="title",
        ),
        migrations.AlterField(
            model_name="client",
            name="additional_info",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="client",
            name="phone_number",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="client",
            name="search_area",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="clients",
                to="agency.area",
            ),
        ),
        migrations.AlterField(
            model_name="deal",
            name="agent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="deals",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="deal",
            name="date",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="property",
            name="address",
            field=models.CharField(max_length=63),
        ),
        migrations.AlterField(
            model_name="property",
            name="description",
            field=models.CharField(max_length=255),
        ),
        migrations.AddConstraint(
            model_name="client",
            constraint=models.UniqueConstraint(
                fields=("email", "phone_number"), name="unique_email_and_phone_number"
            ),
        ),
    ]
