# Generated by Django 4.1.7 on 2023-04-06 09:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("agency", "0020_alter_deal_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="area",
            name="agent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="areas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
