# Generated by Django 4.1.7 on 2023-04-06 09:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("agency", "0021_alter_area_agent"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="area",
            name="unique_name_of_area",
        ),
        migrations.AlterField(
            model_name="area",
            name="agent",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="areas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
