# Generated by Django 4.1.7 on 2023-04-06 09:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agency", "0023_alter_area_agent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deal",
            name="date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
