# Generated by Django 4.1.7 on 2023-04-06 11:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("agency", "0024_alter_deal_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="deal",
            name="deal",
        ),
    ]
