# Generated by Django 4.1.7 on 2023-04-06 11:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("agency", "0025_remove_deal_deal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deal",
            name="agent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="deals",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
