# Generated by Django 4.1.7 on 2023-04-06 11:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("agency", "0026_alter_deal_agent"),
    ]

    operations = [
        migrations.AddField(
            model_name="deal",
            name="additinal_info",
            field=models.CharField(blank=True, max_length=63),
        ),
        migrations.AlterField(
            model_name="deal",
            name="agent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="deals",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
