# Generated by Django 4.1.7 on 2023-04-06 11:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agency", "0027_deal_additinal_info_alter_deal_agent"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="deal",
            name="additinal_info",
        ),
        migrations.AddField(
            model_name="deal",
            name="deal",
            field=models.CharField(default="", max_length=63),
        ),
    ]
