# Generated by Django 4.2 on 2023-04-30 09:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agency", "0032_alter_deal_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="property_type",
            field=models.CharField(
                choices=[
                    ("House", "House"),
                    ("Apartment", "Apartment"),
                    ("Townhouse", "Townhouse"),
                ],
                max_length=63,
            ),
        ),
    ]
